on:
  push:
    tags: ['*']
name: tag
jobs:
  publish:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            artifact_name: bovine
            asset_name: bovine-linux-gnu-amd64
          - os: windows-latest
            artifact_name: bovine.exe
            asset_name: bovine-windows-amd64
          - os: macos-latest
            artifact_name: bovine
            asset_name: bovine-macos-amd64
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --locked
      - run: |
          if [ "${{ github.ref }}" = "*rc*" ]; then
            echo "PRERELEASE=true" >> $GITHUB_ENV
          else
            echo "PRERELEASE=false" >> $GITHUB_ENV
          fi
          echo $PRERELEASE
      - run: |
          VERSION=$(echo ${{ github.ref }} | sed 's/refs\/tags\///g')
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo $VERSION
      - uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ matrix.artifact_name }}
          asset_name: ${{ matrix.asset_name }}
          tag: ${{ github.ref }}
          prerelease: ${{ env.PRERELEASE }}
          release_name: "Bovine ${{ env.VERSION }}"
          body: "Please refer to CHANGELOG.md for information on this release."
